POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "aa",
  "password": "khanhnguyn123456"
}

###

GET http://localhost:5000/api/course
Content-Type: application/json

###

DELETE  http://localhost:5000/api/course/6352d4895d2ce605d0ff1d49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzUyN2Y0NWZkY2VlNWY4OTFkYzYyNzUiLCJpYXQiOjE2NjY0OTMwOTF9.dAvGuOC_4RjddcLIGurqJi-dWz9qICpz7pZTaojan6Y

###
GET http://localhost:5000/api/course/buy
Content-Type: application/json

###
GET http://localhost:5000/api/auth/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzUyN2Y0NWZkY2VlNWY4OTFkYzYyNzUiLCJpYXQiOjE2NjY0OTMwOTF9.dAvGuOC_4RjddcLIGurqJi-dWz9qICpz7pZTaojan6Y

###
POST http://localhost:5000/uploads
Content-Type: application/json

{
  "fieldname": "file",
  "originalname": "1.png",
  "encoding": "7bit",
  "mimetype": "image/png",
  "destination": "./uploads",
  "filename": "1.png",
  "path": "uploads\\1.png",
  "size": 26253
}

###
POST http://localhost:5000/api/auth/asdf
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzUyN2Y0NWZkY2VlNWY4OTFkYzYyNzUiLCJpYXQiOjE2NjY0OTMwOTF9.dAvGuOC_4RjddcLIGurqJi-dWz9qICpz7pZTaojan6Y

###
PUT http://localhost:5000/api/auth/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzY2MWQzYjIzZTNlZDdhZWM3OWRlODMiLCJpYXQiOjE2NzA1NzgzMDB9.ENSnzfCbgGeDEZ29x1yMmSRGRkn2Zb3qbQxlWwellz0

{
  "oldPassword": "khanhnguyn123456",
  "newPassword": "khanhnguyn1234567",
  "reNewPassword": "khanhnguyn1234567"
}

###
PUT http://localhost:5000/api/auth/changeInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzk0Y2Q1ZTE4NGQ3ZmMxOTBmOTUyY2YiLCJpYXQiOjE2NzA2OTY5OTl9.IvPdezSmUMTujlLberbJ_73x31ukHnWlpdmKcL8zjDU

{
  "fullname": "Nguyen Minh Khanh",
  "email": "khanh@gmail.com",
  "phone": "0784546"
}

###
GET http://localhost:5000/api/course/myCourse
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzY2MWQzYjIzZTNlZDdhZWM3OWRlODMiLCJpYXQiOjE2NzA3NTU5MDl9.tg-lA8TylA4_FVsb82F4XD-TKps9i9Nqk0Fv4FXoTSc


