POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "Khanhb1909929",
  "password": "khanhnguyn1234567"
}

###

GET http://localhost:5000/api/course
Content-Type: application/json

###

DELETE  http://localhost:5000/api/course/6352d4895d2ce605d0ff1d49
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzUyN2Y0NWZkY2VlNWY4OTFkYzYyNzUiLCJpYXQiOjE2NjY0OTMwOTF9.dAvGuOC_4RjddcLIGurqJi-dWz9qICpz7pZTaojan6Y

###
GET http://localhost:5000/api/course/buy
Content-Type: application/json

###
GET http://localhost:5000/api/auth/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzUyN2Y0NWZkY2VlNWY4OTFkYzYyNzUiLCJpYXQiOjE2NjY0OTMwOTF9.dAvGuOC_4RjddcLIGurqJi-dWz9qICpz7pZTaojan6Y

###
POST http://localhost:5000/uploads
Content-Type: application/json

{
  "fieldname": "file",
  "originalname": "1.png",
  "encoding": "7bit",
  "mimetype": "image/png",
  "destination": "./uploads",
  "filename": "1.png",
  "path": "uploads\\1.png",
  "size": 26253
}